[pytest]
addopts = -ra --ignore=tests/test_standards.py --ignore=tests/test_generalised.py --ignore=tests/test_integration.py --ignore=tests/test_mpo_simulator.py
testpaths = tests
filterwarnings =
    error::DeprecationWarning:siliqun
